apiVersion: v1
kind: ReplicationController
metadata:
  name: dan01
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: dan01
  template:
    metadata:
      labels:
        app: dan01
    spec:
      serviceAccount: YOUR
      containers:
      - name: dan01
        image: ${docker-registry}/${docker-namespace}/dan01:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080